#!/bin/bash

ps waux | grep node | grep -v grep

echo "starting ..."
## note: start as root, pass env vars to sudo param, this app will downgrade itself once it has initialized
sudo -E /usr/local/bin/node app.js &> log.txt &
echo "$!" > /tmp/shell.pid


cd etherpad-lite/node
node server.js &> log.txt &
echo "$!" > /tmp/epl.pid
cd ../..

sleep 3
ps waux | grep node | grep -v grep

