#!/bin/bash

#cd ~/fc
node app.js &> log.txt &
echo "$!" > /tmp/shell.pid

#cd ~/fc/bruml
#node server.js &> log.txt &
#echo "$!" > /tmp/bruml.pid

cd etherpad-lite/node
node server.js &> log.txt &
echo "$!" > /tmp/epl.pid
#cd ~/fc/etherpad-lite
#./bin/run.sh &> log.txt &
#echo "$!" > /tmp/epl.pid
