#!/bin/bash


cd ~/fc/bruml
node server.js &> log.txt &
echo "$!" > /tmp/bruml.pid

cd ~/fc/etherpad-lite/node
node server.js &> log.txt &
echo "$!" > /tmp/epl.pid

cd ~/fc
node app.js &> log.txt &
echo "$!" > /tmp/shell.pid

